apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1-prod
  labels:
    app: app1
spec:
  selector:
    app: app1
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001